### ISSUE TITLE
init() not working

### ISSUE THREAD

**Issue by tanzeelpr** [amplience/dc-extensions-sdk#41]
I've started to work on an extension but not able to get it initialized. Below is my code snippet. I am just calling the init(); method but the code doesn't really proceed beyond that line. I only see "before init" in console and there is no "after init"

`function App() {
  useEffect(() => {
    const initialize = async () => {
      try {
        console.log('before init');
        const sdk = await init();
        console.log('after init');
      } catch (err) {
        console.error(err);
      }
    }
    initialize();
  }, []);
  return (
    <div className="App">
      Test
    </div>
  );
}`

What is the issue here

**Comment by tanzeelpr** [comment]
Any update around the above issue.. Is this version specific or something i am missing

**Comment by Benj0s** [comment]
Hey,

This is usually caused by loading the extension outside of the Dynamic Content app.  The init function is trying to establish a connection with the Dynamic Content app and will wait until the connection is established before continuing.  If this is the case you will need to register and load the extension in the Dynamic Content app. These docs may help:

[Registering extensions](https://amplience.com/docs/development/registeringextensions.html)
[Developing extensions](https://amplience.com/docs/development/sampleextension.html)

**Comment by tanzeelpr** [comment]
Thanks @Benj0s ,

I understand now, that the extension can only run within the DC application. Working now
